# _quarto.yml
project:
  type: default

bibliography: references.bib
csl: ieee.csl

format:
  pdf:
    documentclass: IEEEtran
    classoption:
      - conference
    toc: false
    number-sections: true
    colorlinks: true
    link-citations: true
